config/routes.rb
Rails.application.routes.draw do

  # дергаем спец. девайзовский метод, который генерит все нужные ему пути
  devise_for :users

  root "events#index"

  resources :events do
    # вложенный ресурс комментов
    resources :comments, only: [:create, :destroy]

    # вложенный ресурс подписок (см. rake routes)
    resources :subscriptions, only: [:create, :destroy]
    # Вложенные в ресурс события ресурсы фотографий
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
# Модель события
class Event < ActiveRecord::Base
  # событие всегда принадлежит юзеру
  belongs_to :user

  # у события много комментариев и подписок
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # у события много фотографий
  has_many :photos, dependent: :destroy

  # у события много подписчиков (объекты User), через таблицу subscriptions, по ключу user_id
  has_many :subscribers, through: :subscriptions, source: :user


  # юзера не может не быть
  validates :user, presence: true

  # категория не может не быть
  validates :category, presence: true

  # заголовок должен быть, и не длиннее 255 букв
  validates :title, presence: true, length: {maximum: 255}

  validates :address, presence: true
  validates :datetime, presence: true

  # Метод, который возвращает всех, кто пойдет на событие:
  # всех подписавшихся и организатора
  def visitors
    (subscribers + [user]).uniq
  end

  CATEGORIES = {
    0 => "Компьютеры и сетевое оборудование",
    1 => "Телефоны и телекоммуникации",
    2 => "Одежда и аксессуары",
    3 => "Бытовая электроника",
    4 => "Багаж и сумки",
    5 => "Ювелирные изделия",
    6 => "Для дома и сада",
    7 => "Часы",
    8 => "Другие категории"
  }

end

app/controllers/events_controller.rb
# Контроллер, управляющий событиями
class EventsController < ApplicationController
  # встроенный в девайз фильтр - посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show, :index]

  # задаем объект @event для экшена show
  before_action :set_event, only: [:show]

  # задаем объект @event от текущего юзера
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  before_action :password_guard!, only: [:show]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    # Болванка модели для формы добавления комментария
    @new_comment = @event.comments.build(params[:comment])

    # Болванка модели для формы подписки
    @new_subscription = @event.subscriptions.build(params[:subscription])

    # Болванка модели для формы добавления фотографии
    @new_photo = @event.photos.build(params[:photo])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      # Используем сообщение из файла локалей ru.yml
      # controllers -> events -> created
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  # Убедитесь, что в secrets.yml задано значение для  secret_key_base
  #
  # production:
  #   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #
  # И оно работает (например на Хероку задана нужная переменная окружения)
  #
  # Тогда куки в рельсах 4 и старше по умолчанию шифруются и хранить там пинкод
  # для данной задачи достаточно безопасно.
  #
  # http://api.rubyonrails.org/classes/ActionDispatch/Session/CookieStore.html
  #
  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    # юзер на чужом событии (или не за логином)
    # проверяем, правильно ли передал пинкод
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      # если правильно, запоминаем в куках этого юзера этот пинкод для данного события
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    # проверяем - верный ли в куках пинкод, если нет — ругаемся
    unless @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
      flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
      render 'password_form'
    end
  end


  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode, :category)
  end
end

app/views/events/_event.html.erb
<div class="col-sm-12 col-sm-2">
  <h3><%= link_to event.title, event_path(event) %></h3>
  <div class="img-thumbnail">
    <a href="<%= event_path(event) %>">
      <%= image_tag event_thumb(event), class: "img-app", alt: "event_jpg", id: "HomeImage" %>
    </a>
    <div class="thumbnail-inner event-info-inner">
      <div class="event-description">
        <div class="buffer-both"><%= event.address %></div>
      </div>
    </div>
  </div>

</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

    <div class="form-group">
      <%= f.label :category %>
      <%= select(:event, :category, Event::CATEGORIES.invert.to_a) %>
    </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="text-center">
  <div class="buffer-both">
    <%= image_tag "logo.jpg", alt: "swap_img",
                  id: "HomeImage",
                  class: "img-circle img-logo" %>
    <%= link_to 'Предложить товар на обмен', new_event_path, class: 'btn btn-success' %>
  </div>

  <div class="row buffer-bottom">
    <%# Рендерим сразу массив товаров, каждый в паршиале 'swaps/swap' %>
    <%= render partial: 'events/event', collection: @events %>
  </div>
</div>
</div>

app/views/events/new.html.erb
<h1>Товар на обмен</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="form-group">
    <%= label 'Пин-код', :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

<%= link_to 'На главную', events_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-8 col-md-8">
      <h2 class="page-header"><%= @event.title %></h2>
      <div class="img-rounded"><%= image_tag(event_photo(@event), class: 'img-thumbnail') %>
      </div>
      <div class="event-photos">
        <%# Выводим все фотографии события %>
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>


        <%# Кнопка вывода формы добавления фотографии %>


        <%# Рисуем форму для добавления новой фотографии (которая будет скрыта) %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="buffer-top">
        <% if current_user_can_edit?(@event) %>
            <div class="buffer-top text-right">
              <%= link_to 'Удалить', event_path(@event), method: :delete, class: 'btn btn-sm btn-danger',
                          data: {confirm: "Вы уверены?"} %>

              <%= link_to "Добавить фотку", '#', class: 'btn btn-primary event-photo-form-link' %>
              <%# Кнопка вывода формы добавления фотографии %>
              <%= link_to 'Изменить описание', edit_event_path(@event), class: 'btn btn-primary' %>
            </div>
        <% end %>
      </div>
      <h5>Добавлено : <%= l @event.datetime, format: :short %></h5>
      <div class="row">
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">Описание</div>
            <div class="panel-body">
              <p><%= @event.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="event-owner text-right">
      <h4>Предлагает обмен:</h4>
      <h3><%= render partial: 'users/user', object: @event.user %></h3>
      <p class="rightstr event-map" id="map" data-address="<%= @event.address %>"></p>
      <div class="event-subscriptions">
        <h4>Хотят поменяться:</h4>
        <div>
          <p>
            <%= render(
                    partial: 'subscriptions/subscription',
                    collection: @event.subscriptions.except(@new_subscription)
                ) %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="event-subscription-form">
        <% if (current_user_can_edit?(@event)) == false %>
            <h4>Хочу меняться:</h4>
            <div>
              <%= render partial: 'subscriptions/form', locals: {subscription: @new_subscription || @event.subscriptions.build} %>
            </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="event-comments buffer-top">
        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>

        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>

      </div>
    </div>
  </div>
</div>
</div>